### ISSUE TITLE
SSO shortcut links support

### ISSUE THREAD

**Issue by maratsh** [pyro2927/AWS_SSO_Containers#22] opened 2024-04-16 15:39 UTC
It will be nice to support new shortcut links feature.
Seems broken right now: after clicking to account container, no link is saved

https://docs.aws.amazon.com/singlesignon/latest/userguide/createshortcutlink.html

**Comment by ghost** [comment] 2024-04-16 21:17
Just a heads up this is a dupe of #21

**Comment by pyro2927** [comment] 2024-06-08 21:37
Resolved as of #24

**Closed as completed by pyro2927** 2024-06-08 21:37 UTC
